name: Build Mac

on:
  push:
    branches: [ main, electron ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions: # Add this block
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build macOS app
      run: npm run dist:mac
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai-summarizer
        path: ./dist_electron/reader-*.dmg